# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "TECH Experience 2017 by Conductor"
email: "tex@conductor.com.br"
description: "conhecimentos e ingressar no mercado de trabalho como profissionais criativos e preparados.

O Tech Experience é um evento único, composto por um ciclo de palestras com profissionais da área de TI,  que tem a finalidade de levar conhecimento técnico aos apaixonados por inovação"
baseurl: ""
url: "https://tex.conductor.com.br"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "x"
googleAnalyticsSiteUrl: "x"
siteVerification: "x-wWpMYhFq-no"

# Organizer Info
organizerName: "Conductor"
organizerAlternateName: "Conductor Tecnologia em meios de pagamentos"
organizerDescription: "Líder em meios de pagamentos"
organizerEmail: "tex@conductor.com.br"
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: "http://lviv.gdg.org.ua/"

# Head
metaKeywords: "cartão, meios de pagamentos, hackthon, hackday, hackweek"
twitterAccount: "@devconductor"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Início"}
# - {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Programação"}
 - {permalink: "/speakers/", text: "Palestrantes"}
# - {permalink: "/team/", text: "Team"}
# - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
 - {link: "https://bit.ly/dfua-c4p", text: "Hackthon"}
rightNavigationButtons:
 - {link: "https://pt.surveymonkey.com/r/texconductor", text: "Inscreva-se"}

# Hero Block
heroImage: "fachda_01.jpg"
heroTitle: "TECH Experience | <typeout>"
eventDate: "08, 18 e 19 de Fevereiro de 2017"
typeoutTextValues: '"", "Palestras", "Hackthon", "3K em premiações", "30 vagas", "Cafeina", "Network", "Cloud Computing", ".NET Core"'
typeoutFallback: "Hackthon"
heroButtons:
 - {link: "https://pt.surveymonkey.com/r/texconductor", text: "Inscreva-se"}
 - {permalink: "/#hackthon", text: "Hackthon"}

# About Block
aboutTitle: "Sobre o TECH Experince 2017"
aboutBlock:
 - {title: "Paletras", image: "microfone.png", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Hackathon", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "30 Vagas", image: "vagas.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }
 - {title: "Cursos", image: "book.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

# Statistic Block
statisticBlockImage: "numeros.jpg"
statisticBlock:
 - {count: "3", specialCharacter: "K", info: "mil reais", detail: "em dinheiro"}
 - {count: "24", specialCharacter: "+", info: "horas", detail: "de pura tecnologia"}
 - {count: "3", specialCharacter: "", info: "palestrantes", detail: "Microsoft Most Value Professional"}
 - {count: "40", specialCharacter: "+", info: "horas", detail: "de treinamento intensivo"}

# Latest News Block
latestNewsTitle: "Novidades"

# Rockstar Speakers Block
rockstarSpeakersImage: "equipe_cdt.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Palestrantes"
rockstarSpeakersButtonText: "Conheça os palestrantes"

# Location Block
locationBlockTitle: "Localização"
eventLocationName: "Conductor Filial João Pessoa"
eventLocationLink: "https://www.google.com.br/maps/place/Conductor+Tecnologia/@-7.1124143,-34.8433881,15z/data=!4m5!3m4!1s0x0:0x4151e5a8e7df7079!8m2!3d-7.1124143!4d-34.8433881"
eventStreetAddress: "R. Antônio Régis de Brito, 15"
eventAddressLocality: "João Pessoa"
eventAddressLocalityRegion: "João Pessoa"
eventPostalCode: "58031-106"
eventAddressCountry: "Paraíba"
eventStartTime: "2017-01-01T06:00"
eventDoorTime: "23:00"
eventEndTime: "2014-10-25T20:00"
eventPlaceCoordinates: "-7.11245422,-34.84339078"
mapCenterCoordinates: "-7.11245422,-34.84339078"
mapMobileCenterCoordinates: "-7.11245422,-34.84339078"

# Venue Block
venueBlockTitle: "Local"
venueBigImage: "venue_2.jpg"
venueSmallImage1: "venue_0.jpg"
venueSmallImage2: "venue_1.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Conductor Tecnologia"
venueFeatures: ["Filial João Pessoa", "Localizado no Bairro dos Estados", "Estrutura moderna e acessível", "3KM do Mar"]

# Tweets Feed Block
tweetsFeedImage: "sala_desenv.jpg"
tweetsFeedTitle: "Siga a hashtag"
twitterHashTag: "conductorTex2017"
#twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Realização"
#partnersTitle: "Parceiros"
#partnersC4sponsorsButton: "Seja um patrocinador"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Garanta logo a sua vaga"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Lembre que as vagas são limitadas"

# Footer
socialLinks:
 - {link: "https://plus.google.com/b/102444623953913144164", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GDGLviv", icon: "twitter"}
 - {link: "https://facebook.com/GDGLviv", icon: "facebook"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "http://www.conductor.com.br", text: "Conductor Tecnologia"}
   - {link: "https://pierlabs.io", text: "PIER {Labs}"}
 -
  title: "Contato"
  links:
   - {link: "mailto:tex@conductor.com.br", text: "tex@conductor.com.br"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Perguntas Frequêntes"}

# Blog
blogTitle: "Últimas Novidades"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences."

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "49.056728, 3.117289"
logisticsMapMobileCenterCoordinates: "48.335365, 23.711648"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction-details.jpg"
directionDetailsTitle: "Get around Lviv"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="http://lwo.aero/en/transport">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Lviv. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Lviv.'}
 - {title: "Hotels", information: 'Lviv has lots of great hotels and hostels. More information will be available later.'}
directionDetailsWideCards:
 -
  title: "Questions?"
  subCards:
   -
    title: "Hotels"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Registration"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
   -
    title: "Attendance Details"
    links:
     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Por que participar?", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Como funciona?", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prêmios"
prizes:
 - {title: "2º Lugar", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1º Lugar", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3º Lugar", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2014-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2014-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
